config/routes.rb
Foods::Application.routes.draw do
  get "destination/angry"
  get "destination/choose"
  get "destination/select"
  get "destination/confirmation"
  get "destination/angry2"
  resources :cards

  get "home/index"
  get "home/beforeMenu1"
  get "home/beforeMenu2"
  get "home/beforeMenu3"
  get "home/beforeMenu4"
  get "home/beforeMenu5"
  get "home/beforeMenu6"

  get "menu/index"
  
  resources :shops
  resources :destination

   root :to => 'home#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "200x200>", :thumb => "100x100>" }
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "200x200>", :thumb => "100x100>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/destination_controller.rb
class DestinationController < ApplicationController
  def angry
  end
  def confirmation
    @shop = Shop.order("RANDOM()").first
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def beforeMenu1
  end
  def beforeMenu2
  end
  def beforeMenu3
  end
  def beforeMenu4
  end
  def beforeMenu5
  end
  def beforeMenu6
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.json
  def new
    @shop = Shop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shop }
    end
  end



  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render json: @shop, status: :created, location: @shop }
      else
        format.html { render action: "new" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.json
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/destination_helper.rb
module DestinationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
<% end %>
      </ul>
    </div>
  	<% end %>
	
	<div class="entryForm">
		<div class="field">
	    	店名:
	    	<%= f.text_field :name %>
		</div>
		<div class="field">
		    写真をアップロードする<br />
		    <%= f.file_field :image %>
		</div>
		
		
		<p><%= f.submit '登録する' %></p>
		
	</div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cards.each do |card| %>
  <tr>
    <td><%= card.name %></td>
    <td><%= link_to 'Show', card %></td>
    <td><%= link_to 'Edit', edit_card_path(card) %></td>
    <td><%= link_to 'Destroy', card, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<!--<h2>スカカードの登録</h2>

<%= render 'form' %>

<%= link_to '戻る', '/menu/index' %>
-->





<div id="wrapper">
	<div class="talk" id="line1">
		<p>
			スカカードの登録をします。
		</p>
		<div class="triangle">
		</div>
	</div>
	<%= render 'form' %>
	<div class="selector enable">
		<p>戻る</p>
		<form action="/menu/index">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
</div>

app/views/cards/show.html.erb
	<div id="wrapper">
	<p id="notice"><%= notice %></p>
	
	<div class="column">
		<div class="photo">
		<%= image_tag @card.image.url(:thumb) %>
		</div>
		
		<div class="article">
			<div class="list shopTitle">
				<p><%= @card.name %></p>
			</div>
		</div>
	</div>
	<div class="selector enable">
		<p>戻る</p>
		<form action="/menu/index">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
</div>

app/views/destination/angry.html.erb
<div id="wrapper onload="jumpPage();">
	<div class="talk" id="line1">
		<p>
			とんでもない奴だ！
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="talk append" id="line2">
		<p>
		一人では決められないといったから、
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="talk append" id="line3">
		<p>
			手伝ってやろうというのに、
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="talk append" id="line4">
		<p>
			恩をあだで返す気か！
		</p>
		<div class="triangle">
		</div>
	</div>
	
	<div class="selector enable">
		<p>黙れ</p>
		<form action="/destination/choose">
		<input type="submit" style="display:none;"/>
		</form>
	</div>

		

app/views/destination/angry2.html.erb
<script language="JavaScript">
<!--
// 一定時間経過後に指定ページにジャンプする
mnt = 10; // 何秒後に移動するか？
url = "http://localhost:3000/destination/choose"; // 移動するアドレス
function jumpPage() {
  location.href = url;
}
setTimeout("jumpPage()",mnt*1000)
//-->
</script>

<div id="wrapper">
	<div class="talk" id="line1">
		<p>
			あんたが行く店は、
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="talk append" id="line2">
		<p>
			地獄の三丁目にある、
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="talk append" id="line3">
		<p>
			地獄一まずいと評判の
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="talk append angryMax" id="line4">
		<p>
			「天使ラーメン」だ！
		</p>
		<div class="triangle">
		</div>
	</div>
	
	<div class="selector enable">
		<p>黙れ</p>
		<form action="/destination/choose">
		<input type="submit" style="display:none;"/>
		</form>
	</div>

		

app/views/destination/choose.html.erb
<div id="wrapper">
    <div id="rollWindow">
	    <div id="rollArea">
		<div class="selector enable">
			<p>????</p>
			<form action="/destination/confirmation">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>今味見してる</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>洗濯中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>洗濯中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="selector">
			<p>選択中</p>
			<form action="/destination/select">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
	</div>
</div>

app/views/destination/confirmation.html.erb
	<div id="wrapper">
		<div class="talk" id="line1">
			<p>
				決まりました。
			</p>
			<div class="triangle">
			</div>
		</div>
		
		<div class="talk append" id="line2">
			<p>
				くどいようですが、
			</p>
			<div class="triangle">
			</div>
		</div>
		<div class="talk append" id="line3">
			<p>
				何があっても、この店に行きますね？
			</p>
			<div class="triangle">
			</div>
		</div>
		<div class="query">
			<div class="choices enable yes">
				<p>はい</p>
				<form action="/shops/<%= @shop.id %>">
				<input type="submit" style="display:none;"/>
				</form>
			</div>
			<div class="choices enable no">
				<p>いやだ</p>
				<form action="/destination/angry2">
				<input type="submit" style="display:none;"/>
				</form>
			</div>
		</div>
	</div>

app/views/destination/display.html.erb
<div id="wrapper">
	<div class="talk" id="line1">
		<p>
			なにか？
		</p>
		<div class="triangle">
		</div>
	</div>
	
	<div class="selector enable">
		<p>メニューを表示</p>
		<form action="/menu/index">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
</div>

app/views/destination/index.html.erb
<div id="wrapper">
	<div class="selector enable startButton">
		<p>Start</p>
		<form action="/destination/select">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
</div>

app/views/destination/select.html.erb
<div id="wrapper">
	<div class="talk" id="line1">
		<p>
			ここで出た結果には、
		</p>
		<div class="triangle">
		</div>
	</div>
	
	<div class="talk append" id="line2">
		<p>
			どんなことがあっても従うと誓いますか？
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="query">
		<div class="choices enable yes">
			<p>はい</p>
			<form action="/destination/choose">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
		<div class="choices enable no">
			<p>いいえ</p>
			<form action="/destination/angry">
			<input type="submit" style="display:none;"/>
			</form>
		</div>
	</div>
</div>

app/views/home/beforeMenu1.html.erb
<div id="wrapper">
	<div class="talk" id="line1">
		<p>
			どこに行くかお困りですね。
		</p>
		<div class="triangle">
		</div>
	</div>
	
	<div class="selector enable">
		<p>メニューを表示</p>
		<form action="/menu/index">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
</div>

app/views/home/beforeMenu2.html.erb
<div id="wrapper">
	<div class="talk" id="line1">
		<p>
			御用ですか。
		</p>
		<div class="triangle">
		</div>
	</div>
	
	<div class="selector enable">
		<p>メニューを表示</p>
		<form action="/menu/index">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
</div>

app/views/home/beforeMenu3.html.erb
<div id="wrapper">
	<div class="talk" id="line1">
		<p>
			お考えがまとまらないんですね。
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="talk append" id="line2">
		<p>
			お手伝い、いたしましょう。
		</p>
		<div class="triangle">
		</div>
	</div>
	
	<div class="selector enable">
		<p>メニューを表示</p>
		<form action="/menu/index">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
</div>

app/views/home/beforeMenu4.html.erb
<div id="wrapper">
	<div class="talk" id="line1">
		<p>
			なにか？
		</p>
		<div class="triangle">
		</div>
	</div>
	
	<div class="selector enable">
		<p>メニューを表示</p>
		<form action="/menu/index">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
</div>

app/views/home/beforeMenu5.html.erb
<div id="wrapper">
	<div class="talk" id="line1">
		<p>
			またかよ！
		</p>
		<div class="triangle">
		</div>
	</div>	
	<div class="selector enable">
		<p>黙れ</p>
		<form action="/menu/index">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
</div>

app/views/home/beforeMenu6.html.erb
<div id="wrapper">
	<div class="talk" id="line1">
		<p>
			たまには、ご自分でお決めになってはどうでしょう。
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="talk append" id="line2">
		<p>
		女性に一番嫌われるのは、なかなか行くところを決められない男だそうですよ、
		つまり、優柔不断ではっきりしないやつは嫌われるんですよ。
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="talk append" id="line3">
		<p>
			あなたは、どうですか？
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="talk append" id="line4">
		<p>
			こんなものに頼るようじゃあ…、
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="talk append" id="line5">
		<p>
			失礼いいすぎました。メニューをどうぞ。
		</p>
		<div class="triangle">
		</div>
	</div>
	
	<div class="selector disable">
		<p>メニューを表示</p>
		<form action="/menu/index">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
	<div class="selector enable">
		<p>黙れ</p>
		<form action="/menu/index">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
</div>

app/views/home/index.html.erb
<div id="wrapper">
	<div class="talk">
		<p>
			さぁ、飯へいこう！
		</p>
		<div class="triangle">
		</div>
	</div>
	<div class="selector" onclick="j();">
		<p>Enter</p>
		<form action="/menu/index">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foods</title>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/cards.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>さあ！飯に行こう！</title>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "menu", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/destination.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>さあ！飯に行こう！</title>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "menu", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>さあ！飯に行こう！</title>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "menu", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/menu.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>さあ！飯に行こう！</title>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "menu", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<div id="wrapper">
	<div class="talk" id="line1">
		<p>
			店のリストです。
		</p>
		<div class="triangle">
		</div>
	</div>
<% @shops.each do |shop| %>
	<div class="column">
		<div class="photo">
		<%= image_tag shop.image.url(:thumb) %>
		</div>
		<div class="article">
			<div class="list shopTitle">
				<p><%= shop.name %></p>
			</div>
			<div class="list shopComment">
				<p><%= shop.comment %></p>
			</div>
		    <div class="order">
				<% if false %>
			    <td><%= link_to 'Show', shop %></td>
			    <% end %>
				<div class="revision editButton">
					<td><%= link_to '変更', edit_shop_path(shop) %></td>
				</div>
				<div class="revision destroyButton">
					<td><%= link_to '削除', shop, confirm: '本当に削除しますか?', method: :delete %></td>
				</div>
			</div>
		</div>
	</div>
<% end %>
	</br>
	</br>
	<div class="selector enable">
		<p>戻る</p>
		<form action="/menu/index">
		<input type="submit" style="display:none;"/>
		</form>
	</div>
</div>